```
// =====================================
// Multilingual Translations
// =====================================
const translations = {
    'zh-TW': {
        page_title: '外國學生申請居留證指南 | Residence Permit Application Guide',
        main_title: '外國學生申請居留證完整指南',
        subtitle: '跟著影片一步步完成申請',
        important_notice: '重要提醒',
        notice_1: '線上申請',
        notice_2: '你要完成身體健康檢查才可以拿到居留證。',
        notice_3: '居留證過期，要罰款 1-5 萬元。',
        step1_title: '準備文件',
        step2_title: '註冊帳號',
        step3_title: '填寫申請',
        step4_title: '繳費完成',
        step1_heading: '步驟一：準備必要文件',
        step2_heading: '步驟二：註冊移民署帳號',
        step3_heading: '步驟三：填寫線上申請表',
        step4_heading: '步驟四：繳費與領證',
        required_docs: '必備文件清單',
        doc_passport: '護照',
        doc_passport_desc: '護照正本及影本',
        doc_visa: '居留簽證',
        doc_visa_desc: '註記「外國留學生」的居留簽證',
        doc_enrollment: '在學證明',
        doc_enrollment_desc: '繳費註冊後可下載或至教務處申請',
        doc_residence: '住宿證明',
        doc_residence_desc: '宿舍住宿證明或租屋契約',
        doc_photo: '照片',
        doc_photo_desc: '白色背景2吋半身脫帽正面相片',
        doc_fee: '費用',
        doc_fee_desc: '新臺幣1,000元（一年期）',
        enrollment_cert_title: '📄 如何取得在學證明',
        method1: '方法一：使用 NTNU APP 下載（推薦）',
        method2: '方法二：i-Portal 網頁下載',
        method3: '方法三：至教務處申請',
        enrollment_app_step1: '下載並登入「NTNU APP」（國立臺灣師範大學APP）',
        enrollment_app_step2: '進入「我的校園」→「學生專區」',
        enrollment_app_step3: '選擇「教務資訊」→「在學證明」',
        enrollment_app_step4: '選擇當學期並點擊「下載PDF」',
        app_note: '💡 APP下載的在學證明已內建教務處電子章戳，無需另外用印！',
        enrollment_step1: '登入校務行政資訊入口網',
        enrollment_step2: '進入「應用系統」→「日間學制教務資訊系統」',
        enrollment_step3: '於左側選單點選「在學證明」並下載',
        enrollment_step4: '確認已繳完學費',
        enrollment_step5: '帶著繳費收據到教務處註冊組申請（費用：NT$10/份）',
        enrollment_important_note: '⚠️ 重要提醒：剛繳完學費的同學，系統可能需要2-3個工作天更新狀態，才能下載在學證明。',
        go_to_portal: '前往校務系統 →',
        residence_cert_title: '🏠 如何取得住宿證明',
        dorm_student: '住學校宿舍：',
        residence_step1: '確認已繳交住宿費用',
        residence_step2: '登入校務行政資訊入口網',
        residence_step3: '進入「學生宿舍相關系統」下載住宿證明',
        off_campus: '住校外：',
        rental_contract: '請提供與房東簽訂的租賃契約（租屋契約）',
        video_not_supported: '您的瀏覽器不支援影片播放',
        video1_caption: '觀看影片學習如何註冊移民署線上申辦系統帳號',
        video2_caption: '跟著影片一步步完成居留證申請表填寫',
        video3_caption: '了解如何完成繳費並領取居留證',
        registration_steps: '註冊步驟說明',
        reg_step1: '前往移民署線上申辦網站：https://reurl.cc/GEbr2p',
        reg_step2: '點選「註冊新帳號」',
        reg_step3: '填寫個人基本資料（護照資訊、聯絡方式等）',
        reg_step4: '設定帳號密碼',
        reg_step5: '驗證電子郵件',
        reg_step6: '完成註冊',
        application_steps: '申請步驟說明',
        app_step1: '登入移民署線上申辦系統',
        app_step2: '選擇「外僑居留證申請」',
        app_step3: '填寫個人基本資料',
        app_step4: '上傳必要文件：',
        upload_enrollment: '在學證明',
        upload_residence: '住宿證明',
        upload_photo: '2吋照片電子檔',
        app_step5: '確認資料無誤',
        app_step6: '送出申請',
        permit_duration: '⏰ 居留證效期說明',
        duration_note1: '初次入國未註冊（未上傳在學證明）：核發6個月效期',
        duration_note2: '初次入國已註冊（上傳在學證明）：核發1年效期',
        duration_note3: '居留證到期前3個月應申請延展',
        payment_steps: '繳費步驟說明',
        pay_step1: '線上申請完成後，系統會產生繳費單',
        pay_step2: '列印繳費單或記下繳費代碼',
        pay_step3: '前往便利商店、郵局或銀行繳費（NT$1,000）',
        pay_step4: '保留繳費收據',
        pay_step5: '等待審核通知（約7-14個工作天）',
        pay_step6: '收到通知後，攜帶護照和收據前往移民署領證',
        congratulations: '恭喜！',
        completion_message: '完成以上步驟後，您就成功申請了台灣居留證！',
        important_reminders: '📌 重要事項提醒',
        reminder1: '居留證到期前 3 個月內，必須延期。',
        reminder2: '如果你搬家，換地址，要在 30 天內告訴移民署。',
        reminder3: '居留證逾期將處新臺幣1萬元至5萬元罰鍰（依逾期天數遞增）',
        reminder4: '如果你的居留證不見了，請馬上告訴移民署。',
        need_help: '需要協助？',
        immigration_office: '內政部移民署',
        immigration_website: '網站：線上申辦系統',
        school_office: '師大國際事務處',
        school_location: '位置：和平校區 普通大樓1樓',
        next_step: '下一步 →',
        prev_step: '← 上一步',
        start_over: '重新開始',
        footer_text: '© 2026 台灣師範大學 - 外國學生居留證申請指南'
    },
    'en': {
        page_title: 'Taiwan Residence Permit Application Guide for International Students',
        main_title: 'Complete Guide for Residence Permit Application',
        subtitle: 'Follow the videos step by step',
        important_notice: 'Important Notice',
        notice_1: 'Online Application',
        notice_2: 'Health examination is required to receive residence permit',
        notice_3: 'Overdue permit will result in NT$10,000-50,000 fine',
        step1_title: 'Prepare Documents',
        step2_title: 'Register Account',
        step3_title: 'Fill Application',
        step4_title: 'Payment',
        step1_heading: 'Step 1: Prepare Required Documents',
        step2_heading: 'Step 2: Register Immigration Office Account',
        step3_heading: 'Step 3: Fill Out Online Application',
        step4_heading: 'Step 4: Payment and Collection',
        required_docs: 'Required Documents',
        doc_passport: 'Passport',
        doc_passport_desc: 'Original and copy of passport',
        doc_visa: 'Resident Visa',
        doc_visa_desc: 'Resident visa marked "Foreign Student"',
        doc_enrollment: 'Enrollment Certificate',
        doc_enrollment_desc: 'Download after registration or apply at Registrar Office',
        doc_residence: 'Residence Proof',
        doc_residence_desc: 'Dormitory certificate or rental contract',
        doc_photo: 'Photo',
        doc_photo_desc: '2-inch photo with white background',
        doc_fee: 'Fee',
        doc_fee_desc: 'NT$1,000 (one-year permit)',
        enrollment_cert_title: '📄 How to Obtain Enrollment Certificate',
        method1: 'Method 1: Download via NTNU APP (Recommended)',
        method2: 'Method 2: i-Portal Web Download',
        method3: 'Method 3: Apply at Registrar Office',
        enrollment_app_step1: 'Download and log in to "NTNU APP" (National Taiwan Normal University APP)',
        enrollment_app_step2: 'Go to "My School" → "Student Zone"',
        enrollment_app_step3: 'Select "Academic Affairs" → "Enrollment Certificate"',
        enrollment_app_step4: 'Select current semester and click "Download PDF"',
        app_note: '💡 Certificates downloaded via APP include built-in official digital stamp - no additional stamping needed!',
        enrollment_step1: 'Log in to Student Portal',
        enrollment_step2: 'Go to "Application Systems" → "Academic Information System"',
        enrollment_step3: 'Click "Certificate of Enrollment" on the left menu to download',
        enrollment_step4: 'Confirm tuition payment',
        enrollment_step5: 'Bring receipt to Registrar Office (Fee: NT$10/copy)',
        enrollment_important_note: '⚠️ Important: After paying tuition, it may take 2-3 working days for the system to update before you can download the certificate.',
        go_to_portal: 'Go to Portal →',
        residence_cert_title: '🏠 How to Obtain Residence Proof',
        dorm_student: 'Dormitory Students:',
        residence_step1: 'Confirm payment of accommodation fees',
        residence_step2: 'Log in to Student Portal',
        residence_step3: 'Download certificate from "Dormitory System"',
        off_campus: 'Off-Campus:',
        rental_contract: 'Provide rental contract signed with landlord',
        video_not_supported: 'Your browser does not support video playback',
        video1_caption: 'Learn how to register an immigration online system account',
        video2_caption: 'Follow the video to complete the application form',
        video3_caption: 'Learn how to complete payment and collect permit',
        registration_steps: 'Registration Steps',
        reg_step1: 'Visit Immigration Office website: https://reurl.cc/GEbr2p',
        reg_step2: 'Click "Register New Account"',
        reg_step3: 'Fill in personal information (passport, contact, etc.)',
        reg_step4: 'Set username and password',
        reg_step5: 'Verify email address',
        reg_step6: 'Complete registration',
        application_steps: 'Application Steps',
        app_step1: 'Log in to Immigration online system',
        app_step2: 'Select "Alien Residence Certificate Application"',
        app_step3: 'Fill in personal information',
        app_step4: 'Upload required documents:',
        upload_enrollment: 'Enrollment certificate',
        upload_residence: 'Residence proof',
        upload_photo: '2-inch photo file',
        app_step5: 'Confirm information',
        app_step6: 'Submit application',
        permit_duration: '⏰ Permit Duration',
        duration_note1: 'First entry without enrollment: 6-month permit',
        duration_note2: 'First entry with enrollment: 1-year permit',
        duration_note3: 'Apply for extension 3 months before expiry',
        payment_steps: 'Payment Steps',
        pay_step1: 'Payment slip will be generated after application',
        pay_step2: 'Print payment slip or note payment code',
        pay_step3: 'Pay at convenience store, post office or bank (NT$1,000)',
        pay_step4: 'Keep payment receipt',
        pay_step5: 'Wait for approval (7-14 working days)',
        pay_step6: 'Collect permit at Immigration Office with passport and receipt',
        congratulations: 'Congratulations!',
        completion_message: 'You have successfully applied for Taiwan residence permit!',
        important_reminders: '📌 Important Reminders',
        reminder1: 'Apply for extension 3 months before expiry',
        reminder2: 'Report address changes within 30 days',
        reminder3: 'Overdue permit will result in NT$10,000-50,000 fine',
        reminder4: 'Keep permit safe, report immediately if lost',
        need_help: 'Need Help?',
        immigration_office: 'Immigration Office',
        immigration_website: 'Website: Online Application System',
        school_office: 'NTNU Office of International Affairs',
        school_location: 'Location: General Building 1F, Heping Campus',
        next_step: 'Next Step →',
        prev_step: '← Previous Step',
        start_over: 'Start Over',
        footer_text: '© 2026 NTNU - International Student Residence Permit Guide'
    },
    'ja': {
        page_title: '外国人学生居留証申請ガイド | Residence Permit Application Guide',
        main_title: '外国人学生居留証申請完全ガイド',
        subtitle: '動画に従ってステップバイステップで申請',
        important_notice: '重要な注意',
        notice_1: 'オンライン申請',
        notice_2: '居留証を受け取るには健康診断を完了する必要があります',
        notice_3: '居留証の期限が切れると1万〜5万台湾ドルの罰金が科せられます',
        step1_title: '書類準備',
        step2_title: 'アカウント登録',
        step3_title: '申請記入',
        step4_title: '支払い',
        step1_heading: 'ステップ1：必要書類の準備',
        step2_heading: 'ステップ2：移民署アカウント登録',
        step3_heading: 'ステップ3：オンライン申請フォーム記入',
        step4_heading: 'ステップ4：支払いと受け取り',
        required_docs: '必要書類リスト',
        doc_passport: 'パスポート',
        doc_passport_desc: 'パスポート原本とコピー',
        doc_visa: '居留ビザ',
        doc_visa_desc: '「Foreign Student」と記載された居留ビザ',
        doc_enrollment: '在学証明書',
        doc_enrollment_desc: '登録後、ダウンロードまたは教務課で申請',
        doc_residence: '居住証明書',
        doc_residence_desc: '寮の証明書または賃貸契約書',
        doc_photo: '写真',
        doc_photo_desc: '背景は白、2インチの脱帽正面写真',
        doc_fee: '手数料',
        doc_fee_desc: '1,000台湾ドル（1年有効）',
        enrollment_cert_title: '📄 在学証明書の取得方法',
        method1: '方法1：NTNUアプリでダウンロード（推奨）',
        method2: '方法2：i-Portalウェブダウンロード',
        method3: '方法3：教務課で申請',
        enrollment_app_step1: '「NTNU APP」（国立台湾師範大学アプリ）をダウンロードしてログイン',
        enrollment_app_step2: '「マイキャンパス」→「学生ゾーン」へ',
        enrollment_app_step3: '「教務情報」→「在学証明書」を選択',
        enrollment_app_step4: '現在の学期を選択し「PDFダウンロード」をクリック',
        app_note: '💡 アプリでダウンロードした証明書には電子印鑑が含まれており、追加の捺印は不要です！',
        enrollment_step1: '校務行政ポータルサイトにログイン',
        enrollment_step2: '「応用システム」→「日間学制教務情報システム」',
        enrollment_step3: '於左側選單點選「在學證明」並下載',
        enrollment_step4: '学費の支払いが完了していることを確認',
        enrollment_step5: '領収書を持って教務課登録係へ（手数料：1部10台湾ドル）',
        enrollment_important_note: '⚠️ 重要：学費支払い後、システムが更新され証明書がダウンロードできるようになるまで2〜3営業日かかる場合があります。',
        go_to_portal: 'ポータルへ移動 →',
        residence_cert_title: '🏠 居住証明書の取得方法',
        dorm_student: '寮生：',
        residence_step1: '宿泊費の支払いが完了していることを確認',
        residence_step2: '校務行政ポータルサイトにログイン',
        residence_step3: '「学生寮関連システム」から証明書をダウンロード',
        off_campus: '学外居住：',
        rental_contract: '大家と署名した賃貸契約書を提出',
        video_not_supported: 'お使いのブラウザは動画再生に対応していません',
        video1_caption: '動画を見て移民署オンライン申請システムのアカウント登録方法を学ぶ',
        video2_caption: '動画に従って居留証申請フォームに記入する',
        video3_caption: '支払いと居留証の受け取り方法を学ぶ',
        registration_steps: '登録手順',
        reg_step1: '移民署オンライン申請サイトへ：https://reurl.cc/GEbr2p',
        reg_step2: '「新規アカウント登録」をクリック',
        reg_step3: '個人基本情報（パスポート情報、連絡先など）を記入',
        reg_step4: 'アカウントとパスワードを設定',
        reg_step5: 'メールアドレスを認証',
        reg_step6: '登録完了',
        application_steps: '申請手順',
        app_step1: '移民署オンラインシステムにログイン',
        app_step2: '「外僑居留証申請」を選択',
        app_step3: '個人基本情報を記入',
        app_step4: '必要書類をアップロード：',
        upload_enrollment: '在学証明書',
        upload_residence: '居住証明書',
        upload_photo: '2インチの写真ファイル',
        app_step5: '情報を確認',
        app_step6: '申請を送信',
        permit_duration: '⏰ 居留証の有効期間',
        duration_note1: '初回入国未登録（在学証明書なし）：6ヶ月有効',
        duration_note2: '初回入国登録済み（在学証明書あり）：1年有効',
        duration_note3: '期限切れの3ヶ月前に延長申請が必要',
        payment_steps: '支払い手順',
        pay_step1: 'オンライン申請完了後、支払い票が発行されます',
        pay_step2: '支払い票を印刷するか、コードを控える',
        pay_step3: 'コンビニ、郵便局、銀行で支払う（1,000台湾ドル）',
        pay_step4: '領収書を保管する',
        pay_step5: '審査通知を待つ（約7〜14営業日）',
        pay_step6: '通知を受け取ったら、パスポートと領収書を持って移民署で受け取る',
        congratulations: 'おめでとうございます！',
        completion_message: '以上の手順を完了すると、台湾居留証の申請が成功します！',
        important_reminders: '📌 重要なリマインダー',
        reminder1: '期限切れの3ヶ月前に延長申請が必要',
        reminder2: '住所変更は30日以内に変更登記が必要',
        reminder3: '期限切れは1万〜5万台湾ドルの罰金',
        reminder4: '居留証は大切に保管し、紛失時は直ちに届け出る',
        need_help: 'ヘルプが必要ですか？',
        immigration_office: '内政部移民署',
        immigration_website: 'ウェブサイト：オンライン申請システム',
        school_office: 'NTNU Office of International Affairs',
        school_location: '場所：和平キャンパス 一般ビル1階',
        next_step: '次へ →',
        prev_step: '← 戻る',
        start_over: '最初からやり直す',
        footer_text: '© 2026 国立台湾師範大学 - 外国人学生居留証申請ガイド'
    },
    'ko': {
        page_title: '외국인 학생 거류증 신청 가이드 | Residence Permit Application Guide',
        main_title: '외국인 학생 거류증 신청 완벽 가이드',
        subtitle: '동영상을 따라 단계별로 신청하세요',
        important_notice: '중요 알림',
        notice_1: '온라인 신청',
        notice_2: '거류증 수령을 위해 건강검진을 반드시 완료해야 합니다',
        notice_3: '거류증 기한 만료 시 1만~5만 대만달러의 벌금이 부과됩니다',
        step1_title: '서류 준비',
        step2_title: '계정 등록',
        step3_title: '신청서 작성',
        step4_title: '납부 완료',
        step1_heading: '1단계: 필수 서류 준비',
        step2_heading: '2단계: 이민서 계정 등록',
        step3_heading: '3단계: 온라인 신청서 작성',
        step4_heading: '4단계: 납부 및 수령',
        required_docs: '필수 서류 목록',
        doc_passport: '여권',
        doc_passport_desc: '여권 원본 및 사본',
        doc_visa: '거류 비자',
        doc_visa_desc: '"Foreign Student"가 표기된 거류 비자',
        doc_enrollment: '재학 증명서',
        doc_enrollment_desc: '등록 후 다운로드하거나 교무처에서 신청',
        doc_residence: '거주 증명서',
        doc_residence_desc: '기숙사 증명서 또는 임대차 계약서',
        doc_photo: '사진',
        doc_photo_desc: '흰색 배경의 2인치 탈모 정면 사진',
        doc_fee: '수수료',
        doc_fee_desc: '1,000 대만달러 (1년 유효)',
        enrollment_cert_title: '📄 재학 증명서 발급 방법',
        method1: '방법 1: NTNU 앱 다운로드 (추천)',
        method2: '방법 2: i-Portal 웹 다운로드',
        method3: '방법 3: 교무처 신청',
        enrollment_app_step1: '"NTNU APP"(국립대만사범대학 앱) 다운로드 및 로그인',
        enrollment_app_step2: '"나의 캠퍼스" → "학생 구역" 이동',
        enrollment_app_step3: '"교무 정보" → "재학 증명서" 선택',
        enrollment_app_step4: '현재 학기 선택 후 "PDF 다운로드" 클릭',
        app_note: '💡 앱에서 다운로드한 증명서는 전자 도장이 포함되어 있어 별도 날인이 필요 없습니다!',
        enrollment_step1: '학교 행정 정보 포털 로그인',
        enrollment_step2: '"응용 시스템" → "주간 학제 교무 정보 시스템" 이동',
        enrollment_step3: '왼쪽 메뉴에서 "재학 증명서"를 클릭하고 다운로드',
        enrollment_step4: '등록금 납부 확인',
        enrollment_step5: '영수증을 지참하여 교무처 등록팀 신청 (비용: 10 대만달러/매)',
        enrollment_important_note: '⚠️ 중요: 등록금 납부 후 시스템 업데이트 및 증명서 다운로드까지 2-3 영업일이 소요될 수 있습니다.',
        go_to_portal: '포털 바로가기 →',
        residence_cert_title: '🏠 거주 증명서 발급 방법',
        dorm_student: '기숙사 거주:',
        residence_step1: '기숙사비 납부 확인',
        residence_step2: '학교 행정 정보 포털 로그인',
        residence_step3: '"학생 기숙사 관련 시스템"에서 증명서 다운로드',
        off_campus: '교외 거주:',
        residence_contract: '집주인과 서명한 임대차 계약서 제출',
        video_not_supported: '브라우저가 동영상을 지원하지 않습니다',
        video1_caption: '이민서 온라인 신청 시스템 계정 등록 방법 영상 시청',
        video2_caption: '영상을 따라 거류증 신청서 작성하기',
        video3_caption: '납부 및 거류증 수령 방법 알아보기',
        registration_steps: '등록 단계 설명',
        reg_step1: '이민서 온라인 신청 사이트 방문: https://reurl.cc/GEbr2p',
        reg_step2: '"새 계정 등록" 클릭',
        reg_step3: '개인 기본 정보 작성 (여권 정보, 연락처 등)',
        reg_step4: '계정 및 비밀번호 설정',
        reg_step5: '이메일 인증',
        reg_step6: '등록 완료',
        application_steps: '신청 단계 설명',
        app_step1: '이민서 온라인 시스템 로그인',
        app_step2: '"외국인 거류증 신청" 선택',
        app_step3: '개인 기본 정보 작성',
        app_step4: '필수 서류 업로드:',
        upload_enrollment: '재학 증명서',
        upload_residence: '거주 증명서',
        upload_photo: '2인치 사진 파일',
        app_step5: '정보 확인',
        app_step6: '신청 제출',
        permit_duration: '⏰ 거류증 유효 기간',
        duration_note1: '최초 입국 미등록 (재학 증명서 미제출): 6개월 유효',
        duration_note2: '최초 입국 등록 완료 (재학 증명서 제출): 1년 유효',
        duration_note3: '만료 3개월 전 연장 신청 필수',
        payment_steps: '납부 단계 설명',
        pay_step1: '온라인 신청 완료 후 납부 고지서 생성',
        pay_step2: '고지서 출력 또는 납부 코드 숙지',
        pay_step3: '편의점, 우체국, 은행에서 납부 (1,000 대만달러)',
        pay_step4: '납부 영수증 보관',
        pay_step5: '심사 통지 대기 (약 7-14 영업일)',
        pay_step6: '통지 수신 후 여권과 영수증 지참하여 이민서 방문 수령',
        congratulations: '축하합니다!',
        completion_message: '위 단계를 완료하면 대만 거류증 신청이 완료됩니다!',
        important_reminders: '📌 중요 사항 알림',
        reminder1: '만료 3개월 전 연장 신청 필수',
        reminder2: '거주지 변경 시 30일 이내 변경 신고',
        reminder3: '기한 만료 시 1만~5만 대만달러 벌금',
        reminder4: '거류증 보관 주의, 분실 시 즉시 신고',
        need_help: '도움이 필요하신가요?',
        immigration_office: '내정부 이민서',
        immigration_website: '웹사이트: 온라인 신청 시스템',
        school_office: 'NTNU Office of International Affairs',
        school_location: '위치: 화평캠퍼스 보통대루 1층',
        next_step: '다음 단계 →',
        prev_step: '← 이전 단계',
        start_over: '처음부터 다시',
        footer_text: '© 2026 국립대만사범대학 - 외국인 학생 거류증 신청 가이드'
    },
    'vi': {
        page_title: 'Hướng dẫn xin thẻ cư trú cho sinh viên nước ngoài | Residence Permit Application Guide',
        main_title: 'Hướng dẫn toàn tập xin thẻ cư trú',
        subtitle: 'Làm theo video từng bước để hoàn thành',
        important_notice: 'Lưu ý quan trọng',
        notice_1: 'Đăng ký trực tuyến',
        notice_2: 'Phải hoàn thành kiểm tra sức khỏe mới được nhận thẻ',
        notice_3: 'Quá hạn thẻ cư trú sẽ bị phạt từ 10.000 đến 50.000 Đài tệ',
        step1_title: 'Chuẩn bị hồ sơ',
        step2_title: 'Đăng ký tài khoản',
        step3_title: 'Điền đơn',
        step4_title: 'Nộp phí',
        step1_heading: 'Bước 1: Chuẩn bị giấy tờ cần thiết',
        step2_heading: 'Bước 2: Đăng ký tài khoản Sở Di dân',
        step3_heading: 'Bước 3: Điền đơn đăng ký trực tuyến',
        step4_heading: 'Bước 4: Nộp phí và Nhận thẻ',
        required_docs: 'Danh sách giấy tờ',
        doc_passport: 'Hộ chiếu',
        doc_passport_desc: 'Bản gốc và bản sao hộ chiếu',
        doc_visa: 'Visa cư trú',
        doc_visa_desc: 'Visa cư trú có ghi chú "Foreign Student"',
        doc_enrollment: 'Giấy chứng nhận đang học',
        doc_enrollment_desc: 'Tải về sau khi đăng ký hoặc xin tại Phòng Đào tạo',
        doc_residence: 'Chứng minh cư trú',
        doc_residence_desc: 'Giấy chứng nhận ở ký túc xá hoặc hợp đồng thuê nhà',
        doc_photo: 'Ảnh thẻ',
        doc_photo_desc: 'Ảnh thẻ 2 inch nền trắng, không đội mũ',
        doc_fee: 'Phí',
        doc_fee_desc: '1.000 Đài tệ (thời hạn 1 năm)',
        enrollment_cert_title: '📄 Cách lấy giấy chứng nhận đang học',
        method1: 'Cách 1: Tải qua Ứng dụng NTNU (Khuyên dùng)',
        method2: 'Cách 2: Tải qua mạng i-Portal',
        method3: 'Cách 3: Xin tại Phòng Đào tạo',
        enrollment_app_step1: 'Tải và đăng nhập "NTNU APP"',
        enrollment_app_step2: 'Vào "Khuôn viên của tôi" → "Khu vực sinh viên"',
        enrollment_app_step3: 'Chọn "Thông tin học vụ" → "Giấy chứng nhận đang học"',
        enrollment_app_step4: 'Chọn học kỳ hiện tại và nhấn "Tải PDF"',
        app_note: '💡 Giấy chứng nhận tải từ APP đã có dấu điện tử, không cần đóng dấu thêm!',
        enrollment_step1: 'Đăng nhập Cổng thông tin Hành chính Trường học',
        enrollment_step2: 'Vào "Hệ thống thông tin học vụ" → "Liên quan đến học tịch"',
        enrollment_step3: 'Chọn "Giấy chứng nhận đang học học kỳ này" và tải về',
        enrollment_step4: 'Xác nhận đã đóng học phí',
        enrollment_step5: 'Mang biên lai đến Tổ Đăng ký Phòng Đào tạo (Phí: 10 Đài tệ/bản)',
        enrollment_important_note: '⚠️ Quan trọng: Sau khi đóng học phí, hệ thống cần 2-3 ngày làm việc để cập nhật trước khi bạn có thể tải giấy chứng nhận.',
        go_to_portal: 'Đến Cổng thông tin →',
        residence_cert_title: '🏠 Cách lấy chứng minh cư trú',
        dorm_student: 'Ở ký túc xá:',
        residence_step1: 'Xác nhận đã đóng phí ký túc xá',
        residence_step2: 'Đăng nhập Cổng thông tin Hành chính',
        residence_step3: 'Tải giấy chứng nhận từ "Hệ thống quản lý KTX"',
        off_campus: 'Ở ngoài trường:',
        rental_contract: 'Cung cấp hợp đồng thuê nhà đã ký với chủ nhà',
        video_not_supported: 'Trình duyệt của bạn không hỗ trợ phát video',
        video1_caption: 'Xem video cách đăng ký tài khoản hệ thống trực tuyến',
        video2_caption: 'Làm theo video để điền đơn xin thẻ cư trú',
        video3_caption: 'Tìm hiểu cách nộp phí và nhận thẻ',
        registration_steps: 'Các bước đăng ký',
        reg_step1: 'Truy cập trang web Sở Di dân: https://reurl.cc/GEbr2p',
        reg_step2: 'Chọn "Đăng ký tài khoản mới"',
        reg_step3: 'Điền thông tin cơ bản (hộ chiếu, liên lạc...)',
        reg_step4: 'Thiết lập tài khoản và mật khẩu',
        reg_step5: 'Xác thực email',
        reg_step6: 'Hoàn tất đăng ký',
        application_steps: 'Các bước nộp đơn',
        app_step1: 'Đăng nhập hệ thống trực tuyến Sở Di dân',
        app_step2: 'Chọn "Xin thẻ cư trú cho người nước ngoài"',
        app_step3: 'Điền thông tin cá nhân',
        app_step4: 'Tải lên giấy tờ cần thiết:',
        upload_enrollment: 'Giấy chứng nhận đang học',
        upload_residence: 'Chứng minh cư trú',
        upload_photo: 'File ảnh 2 inch',
        app_step5: 'Xác nhận thông tin',
        app_step6: 'Gửi đơn',
        permit_duration: '⏰ Thời hạn thẻ cư trú',
        duration_note1: 'Nhập cảnh lần đầu chưa đăng ký (không có giấy chứng nhận học): cấp 6 tháng',
        duration_note2: 'Nhập cảnh lần đầu đã đăng ký (có giấy chứng nhận học): cấp 1 năm',
        duration_note3: 'Phải xin gia hạn 3 tháng trước khi hết hạn',
        payment_steps: 'Các bước nộp phí',
        pay_step1: 'Sau khi nộp đơn xong, hệ thống sẽ tạo phiếu thu',
        pay_step2: 'In phiếu thu hoặc ghi lại mã thanh toán',
        pay_step3: 'Nộp tiền tại cửa hàng tiện lợi, bưu điện hoặc ngân hàng (1.000 Đài tệ)',
        pay_step4: 'Giữ lại biên lai nộp tiền',
        pay_step5: 'Chờ thông báo xét duyệt (khoảng 7-14 ngày làm việc)',
        pay_step6: 'Sau khi nhận thông báo, mang hộ chiếu và biên lai đến Sở Di dân nhận thẻ',
        congratulations: 'Chúc mừng!',
        completion_message: 'Hoàn thành các bước trên, bạn đã xin thành công thẻ cư trú Đài Loan!',
        important_reminders: '📌 Nhắc nhở quan trọng',
        reminder1: 'Gia hạn thẻ 3 tháng trước khi hết hạn',
        reminder2: 'Thay đổi địa chỉ phải đăng ký trong vòng 30 ngày',
        reminder3: 'Quá hạn thẻ bị phạt 10.000 - 50.000 Đài tệ',
        reminder4: 'Bảo quản thẻ cẩn thận, mất phải báo ngay',
        need_help: 'Cần hỗ trợ?',
        immigration_office: 'Sở Di dân - Bộ Nội vụ',
        immigration_website: 'Website: Hệ thống trực tuyến',
        school_office: 'Văn phòng Quốc tế NTNU',
        school_location: 'Địa điểm: Tầng 1 Tòa nhà Phổ thông, Cơ sở Hòa Bình',
        next_step: 'Bước tiếp theo →',
        prev_step: '← Bước trước',
        start_over: 'Bắt đầu lại',
        footer_text: '© 2026 NTNU - Hướng dẫn xin thẻ cư trú cho sinh viên nước ngoài'
    },
    'th': {
        page_title: 'คู่มือสมัครใบถิ่นที่อยู่สำหรับนักเรียนต่างชาติ | Residence Permit Application Guide',
        main_title: 'คู่มือครบวงจรสำหรับการสมัครใบถิ่นที่อยู่',
        subtitle: 'ทำตามวิดีโอทีละขั้นตอน',
        important_notice: 'ข้อควรระวังสำคัญ',
        notice_1: 'สมัครออนไลน์',
        notice_2: 'ต้องตรวจสุขภาพให้เรียบร้อยจึงจะรับใบถิ่นที่อยู่ได้',
        notice_3: 'หากใบถิ่นที่อยู่หมดอายุจะมีโทษปรับ 10,000-50,000 ดอลลาร์ไต้หวัน',
        step1_title: 'เตรียมเอกสาร',
        step2_title: 'ลงทะเบียนบัญชี',
        step3_title: 'กรอกใบสมัคร',
        step4_title: 'ชำระเงิน',
        step1_heading: 'ขั้นตอนที่ 1: เตรียมเอกสารที่จำเป็น',
        step2_heading: 'ขั้นตอนที่ 2: ลงทะเบียนบัญชีสำนักงานตรวจคนเข้าเมือง',
        step3_heading: 'ขั้นตอนที่ 3: กรอกแบบฟอร์มออนไลน์',
        step4_heading: 'ขั้นตอนที่ 4: ชำระเงินและรับบัตร',
        required_docs: 'รายการเอกสารที่ต้องใช้',
        doc_passport: 'หนังสือเดินทาง',
        doc_passport_desc: 'ตัวจริงและสำเนา',
        doc_visa: 'วีซ่าผู้อยู่อาศัย',
        doc_visa_desc: 'วีซ่าที่มีหมายเหตุ "Foreign Student"',
        doc_enrollment: 'ใบรับรองการเป็นนักเรียน',
        doc_enrollment_desc: 'ดาวน์โหลดหลังลงทะเบียนหรือขอที่สำนักทะเบียน',
        doc_residence: 'หลักฐานที่อยู่',
        doc_residence_desc: 'ใบรับรองหอพักหรือสัญญาเช่าบ้าน',
        doc_photo: 'รูปถ่าย',
        doc_photo_desc: 'รูปถ่ายหน้าตรงไม่สวมหมวกขนาด 2 นิ้ว พื้นหลังสีขาว',
        doc_fee: 'ค่าธรรมเนียม',
        doc_fee_desc: '1,000 ดอลลาร์ไต้หวัน (อายุ 1 ปี)',
        enrollment_cert_title: '📄 วิธีขอใบรับรองการเป็นนักเรียน',
        method1: 'วิธีที่ 1: ดาวน์โหลดผ่านแอป NTNU (แนะนำ)',
        method2: 'วิธีที่ 2: ดาวน์โหลดผ่านเว็บ i-Portal',
        method3: 'วิธีที่ 3: ขอที่สำนักทะเบียน',
        enrollment_app_step1: 'ดาวน์โหลดและเข้าสู่ระบบ "NTNU APP"',
        enrollment_app_step2: 'ไปที่ "วิทยาเขตของฉัน" → "โซนนักเรียน"',
        enrollment_app_step3: 'เลือก "ข้อมูลวิชาการ" → "ใบรับรองสถานะนักเรียน"',
        enrollment_app_step4: 'เลือกภาคการศึกษาปัจจุบันและกด "ดาวน์โหลด PDF"',
        app_note: '💡 ใบรับรองจากแอปมีตราประทับอิเล็กทรอนิกส์แล้ว ไม่ต้องประทับตราเพิ่ม!',
        enrollment_step1: 'เข้าสู่ระบบพอร์ทัลข้อมูลบริหารโรงเรียน',
        enrollment_step2: 'เข้าสู่ "ระบบสารสนเทศวิชาการ" → "ทะเบียนนักเรียน"',
        enrollment_step3: 'เลือก "ใบรับรองการเป็นนักเรียนภาคการศึกษานี้" และดาวน์โหลด',
        enrollment_step4: 'ยืนยันว่าชำระค่าเทอมแล้ว',
        enrollment_step5: 'นำใบเสร็จไปยื่นที่สำนักทะเบียน (ค่าธรรมเนียม: 10 ดอลลาร์/ชุด)',
        enrollment_important_note: '⚠️ สำคัญ: หลังชำระค่าเทอม ระบบอาจใช้เวลา 2-3 วันทำการในการอัปเดตก่อนที่จะดาวน์โหลดใบรับรองได้',
        go_to_portal: 'ไปที่พอร์ทัล →',
        residence_cert_title: '🏠 วิธีขอหลักฐานที่อยู่',
        dorm_student: 'นักเรียนหอพัก:',
        residence_step1: 'ยืนยันการชำระค่าหอพัก',
        residence_step2: 'เข้าสู่ระบบพอร์ทัลข้อมูลบริหาร',
        residence_step3: 'ดาวน์โหลดใบรับรองจาก "ระบบหอพักนักเรียน"',
        off_campus: 'พักนอกมหาวิทยาลัย:',
        rental_contract: 'เตรียมสัญญาเช่าที่ลงนามร่วมกับเจ้าของบ้าน',
        video_not_supported: 'เบราว์เซอร์ของคุณไม่รองรับการเล่นวิดีโอ',
        video1_caption: 'ดูวิดีโอวิธีลงทะเบียนบัญชีระบบออนไลน์',
        video2_caption: 'ทำตามวิดีโอเพื่อกรอกแบบฟอร์มขอใบถิ่นที่อยู่',
        video3_caption: 'เรียนรู้วิธีชำระเงินและรับบัตร',
        registration_steps: 'ขั้นตอนการลงทะเบียน',
        reg_step1: 'ไปที่เว็บไซต์สำนักงานตรวจคนเข้าเมือง: https://reurl.cc/GEbr2p',
        reg_step2: 'คลิก "ลงทะเบียนบัญชีใหม่"',
        reg_step3: 'กรอกข้อมูลส่วนตัว (หนังสือเดินทาง, ข้อมูลติดต่อ ฯลฯ)',
        reg_step4: 'ตั้งชื่อบัญชีและรหัสผ่าน',
        reg_step5: 'ยืนยันอีเมล',
        reg_step6: 'ลงทะเบียนเสร็จสมบูรณ์',
        application_steps: 'ขั้นตอนการสมัคร',
        app_step1: 'เข้าสู่ระบบออนไลน์สำนักงานตรวจคนเข้าเมือง',
        app_step2: 'เลือก "สมัครใบถิ่นที่อยู่สำหรับชาวต่างชาติ"',
        app_step3: 'กรอกข้อมูลส่วนตัว',
        app_step4: 'อัปโหลดเอกสารที่จำเป็น:',
        upload_enrollment: 'ใบรับรองการเป็นนักเรียน',
        upload_residence: 'หลักฐานที่อยู่',
        upload_photo: 'ไฟล์รูปถ่าย 2 นิ้ว',
        app_step5: 'ตรวจสอบข้อมูล',
        app_step6: 'ส่งใบสมัคร',
        permit_duration: '⏰ อายุใบถิ่นที่อยู่',
        duration_note1: 'เข้าประเทศครั้งแรกยังไม่ลงทะเบียน: อายุ 6 เดือน',
        duration_note2: 'เข้าประเทศครั้งแรกและลงทะเบียนแล้ว: อายุ 1 ปี',
        duration_note3: 'ต้องต่ออายุก่อนหมดอายุ 3 เดือน',
        payment_steps: 'ขั้นตอนการชำระเงิน',
        pay_step1: 'หลังจากสมัครเสร็จ ระบบจะสร้างใบชำระเงิน',
        pay_step2: 'พิมพ์ใบชำระเงินหรือจดรหัส',
        pay_step3: 'ชำระที่ร้านสะดวกซื้อ ไปรษณีย์ หรือธนาคาร (1,000 ดอลลาร์)',
        pay_step4: 'เก็บใบเสร็จไว้',
        pay_step5: 'รอการตรวจสอบ (ประมาณ 7-14 วันทำการ)',
        pay_step6: 'เมื่อได้รับแจ้ง ให้นำหนังสือเดินทางและใบเสร็จไปรับบัตรที่สำนักงาน',
        congratulations: 'ยินดีด้วย!',
        completion_message: 'เมื่อทำตามขั้นตอนข้างต้น คุณก็สมัครใบถิ่นที่อยู่ไต้หวันสำเร็จแล้ว!',
        important_reminders: '📌 ข้อควรจำสำคัญ',
        reminder1: 'ต่ออายุก่อนบัตรหมดอายุ 3 เดือน',
        reminder2: 'เปลี่ยนที่อยู่ต้องแจ้งภายใน 30 วัน',
        reminder3: 'บัตรหมดอายุมีโทษปรับสูงสุด 50,000 ดอลลาร์',
        reminder4: 'เก็บรักษาบัตรให้ดี หากหายต้องแจ้งทันที',
        need_help: 'ต้องการความช่วยเหลือ?',
        immigration_office: 'สำนักงานตรวจคนเข้าเมือง',
        immigration_website: 'เว็บไซต์: ระบบสมัครออนไลน์',
        school_office: 'NTNU Office of International Affairs',
        school_location: 'สถานที่: อาคารทั่วไป ชั้น 1 วิทยาเขตเหอผิง',
        next_step: 'ขั้นตอนถัดไป →',
        prev_step: '← ย้อนกลับ',
        start_over: 'เริ่มใหม่',
        footer_text: '© 2026 NTNU - คู่มือสมัครใบถิ่นที่อยู่สำหรับนักเรียนต่างชาติ'
    },
    'id': {
        page_title: 'Panduan Permohonan Izin Tinggal Mahasiswa Asing | Residence Permit Guide',
        main_title: 'Panduan Lengkap Izin Tinggal Mahasiswa Asing',
        subtitle: 'Ikuti video langkah demi langkah',
        important_notice: 'Pemberitahuan Penting',
        notice_1: 'Aplikasi Online',
        notice_2: 'Wajib menyelesaikan pemeriksaan kesehatan untuk mengambil izin tinggal',
        notice_3: 'Izin tinggal kadaluarsa didenda NT$10.000-50.000',
        step1_title: 'Persiapan Dokumen',
        step2_title: 'Daftar Akun',
        step3_title: 'Isi Formulir',
        step4_title: 'Pembayaran',
        step1_heading: 'Langkah 1: Siapkan Dokumen Wajib',
        step2_heading: 'Langkah 2: Daftar Akun Imigrasi',
        step3_heading: 'Langkah 3: Isi Formulir Online',
        step4_heading: 'Langkah 4: Pembayaran & Pengambilan',
        required_docs: 'Daftar Dokumen',
        doc_passport: 'Paspor',
        doc_passport_desc: 'Asli dan fotokopi',
        doc_visa: 'Visa Huni',
        doc_visa_desc: 'Visa dengan keterangan "Foreign Student"',
        doc_enrollment: 'Surat Keterangan Mahasiswa',
        doc_enrollment_desc: 'Unduh setelah registrasi atau minta di Biro Akademik',
        doc_residence: 'Bukti Tempat Tinggal',
        doc_residence_desc: 'Surat asrama atau kontrak sewa rumah',
        doc_photo: 'Foto',
        doc_photo_desc: 'Foto 2 inci latar putih tanpa topi',
        doc_fee: 'Biaya',
        doc_fee_desc: 'NT$1.000 (berlaku 1 tahun)',
        enrollment_cert_title: '📄 Cara Dapatkan Surat Keterangan Mahasiswa',
        method1: 'Cara 1: Unduh via Aplikasi NTNU (Disarankan)',
        method2: 'Cara 2: Unduh via Web i-Portal',
        method3: 'Cara 3: Minta di Biro Akademik',
        enrollment_app_step1: 'Unduh & login "NTNU APP"',
        enrollment_app_step2: 'Masuk "Kampus Saya" → "Zona Mahasiswa"',
        enrollment_app_step3: 'Pilih "Info Akademik" → "Surat Keterangan Mahasiswa"',
        enrollment_app_step4: 'Pilih semester ini & klik "Unduh PDF"',
        app_note: '💡 Surat dari APP sudah ada stempel digital resmi, tidak perlu cap lagi!',
        enrollment_step1: 'Login Portal Informasi Administrasi Sekolah',
        enrollment_step2: 'Masuk "Sistem Informasi Akademik" → "Status Mahasiswa"',
        enrollment_step3: 'Pilih "Surat Keterangan Mahasiswa Semester Ini" & unduh',
        enrollment_step4: 'Pastikan uang kuliah sudah lunas',
        enrollment_step5: 'Bawa kuitansi ke Bagian Registrasi (Biaya: NT$10/lembar)',
        enrollment_important_note: '⚠️ Penting: Setelah bayar uang kuliah, sistem butuh 2-3 hari kerja untuk update sebelum surat bisa diunduh.',
        go_to_portal: 'Ke Portal →',
        residence_cert_title: '🏠 Cara Dapatkan Bukti Tempat Tinggal',
        dorm_student: 'Mahasiswa Asrama:',
        residence_step1: 'Pastikan biaya asrama sudah lunas',
        residence_step2: 'Login Portal Informasi Administrasi',
        residence_step3: 'Unduh surat dari "Sistem Asrama Mahasiswa"',
        off_campus: 'Tinggal di Luar:',
        rental_contract: 'Siapkan kontrak sewa yang ditandatangani pemilik rumah',
        video_not_supported: 'Browser Anda tidak mendukung pemutaran video',
        video1_caption: 'Tonton video cara daftar akun sistem online imigrasi',
        video2_caption: 'Ikuti video untuk mengisi formulir izin tinggal',
        video3_caption: 'Pelajari cara pembayaran dan pengambilan kartu',
        registration_steps: 'Langkah Pendaftaran',
        reg_step1: 'Buka website Imigrasi: https://reurl.cc/GEbr2p',
        reg_step2: 'Klik "Daftar Akun Baru"',
        reg_step3: 'Isi data dasar (paspor, kontak, dll)',
        reg_step4: 'Atur akun dan kata sandi',
        reg_step5: 'Verifikasi email',
        reg_step6: 'Pendaftaran selesai',
        application_steps: 'Langkah Pengajuan',
        app_step1: 'Login sistem online Imigrasi',
        app_step2: 'Pilih "Pengajuan Izin Tinggal WNA"',
        app_step3: 'Isi data pribadi',
        app_step4: 'Unggah dokumen:',
        upload_enrollment: 'Surat keterangan mahasiswa',
        upload_residence: 'Bukti tempat tinggal',
        upload_photo: 'File foto 2 inci',
        app_step5: 'Konfirmasi data',
        app_step6: 'Kirim pengajuan',
        permit_duration: '⏰ Masa Berlaku Izin Tinggal',
        duration_note1: 'Masuk pertama belum daftar ulang: berlaku 6 bulan',
        duration_note2: 'Masuk pertama sudah daftar ulang: berlaku 1 tahun',
        duration_note3: 'Perpanjang 3 bulan sebelum masa berlaku habis',
        payment_steps: 'Langkah Pembayaran',
        pay_step1: 'Setelah pengajuan selesai, slip pembayaran muncul',
        pay_step2: 'Cetak slip atau catat kode bayar',
        pay_step3: 'Bayar di minimarket, kantor pos, atau bank (NT$1.000)',
        pay_step4: 'Simpan bukti pembayaran',
        pay_step5: 'Tunggu notifikasi (sekitar 7-14 hari kerja)',
        pay_step6: 'Setelah ada notifikasi, bawa paspor & resi ke Imigrasi',
        congratulations: 'Selamat!',
        completion_message: 'Setelah langkah di atas, Anda berhasil mengajukan Izin Tinggal Taiwan!',
        important_reminders: '📌 Pengingat Penting',
        reminder1: 'Perpanjang 3 bulan sebelum kadaluarsa',
        reminder2: 'Pindah alamat lapor dalam 30 hari',
        reminder3: 'Terlambat perpanjang denda hingga NT$50.000',
        reminder4: 'Jaga kartu baik-baik, hilang segera lapor',
        need_help: 'Butuh Bantuan?',
        immigration_office: 'Kantor Imigrasi',
        immigration_website: 'Website: Sistem Online',
        school_office: 'Kantor Urusan Internasional NTNU',
        school_location: 'Lokasi: Kampus Heping, Gedung Umum Lt. 1',
        next_step: 'Langkah Selanjutnya →',
        prev_step: '← Sebelumnya',
        start_over: 'Mulai Ulang',
        footer_text: '© 2026 NTNU - Panduan Aplikasi Izin Tinggal Mahasiswa Asing'
    },
    'fr': {
        page_title: 'Guide de demande de titre de séjour pour étudiants étrangers | Residence Permit Guide',
        main_title: 'Guide complet pour le titre de séjour',
        subtitle: 'Suivez les vidéos étape par étape',
        important_notice: 'Avis Important',
        notice_1: 'Candidature en ligne',
        notice_2: 'Lexamen médical est requis pour recevoir le titre',
        notice_3: 'Une amende de 10 000 à 50 000 NT$ pour titre expiré',
        step1_title: 'Documents',
        step2_title: 'Inscription',
        step3_title: 'Formulaire',
        step4_title: 'Paiement',
        step1_heading: 'Étape 1 : Préparer les documents requis',
        step2_heading: 'Étape 2 : Créer un compte Immigration',
        step3_heading: 'Étape 3 : Remplir le formulaire en ligne',
        step4_heading: 'Étape 4 : Paiement et Retrait',
        required_docs: 'Documents Requis',
        doc_passport: 'Passeport',
        doc_passport_desc: 'Original et photocopie',
        doc_visa: 'Visa de Résident',
        doc_visa_desc: 'Visa portant la mention "Foreign Student"',
        doc_enrollment: 'Certificat de Scolarité',
        doc_enrollment_desc: 'Télécharger après inscription ou demander au Bureau',
        doc_residence: 'Preuve de Résidence',
        doc_residence_desc: 'Attestation de dortoir ou contrat de location',
        doc_photo: 'Photo',
        doc_photo_desc: 'Photo 2 pouces fond blanc, tête nue',
        doc_fee: 'Frais',
        doc_fee_desc: '1 000 NT$ (validité 1 an)',
        enrollment_cert_title: '📄 Comment obtenir le certificat de scolarité',
        method1: 'Méthode 1 : Via l\'application NTNU (Recommandé)',
        method2: 'Méthode 2 : Téléchargement Web i-Portal',
        method3: 'Méthode 3 : Au Bureau des Inscriptions',
        enrollment_app_step1: 'Télécharger et se connecter à "NTNU APP"',
        enrollment_app_step2: 'Aller dans "Mon Campus" → "Zone Étudiant"',
        enrollment_app_step3: 'Choisir "Infos Académiques" → "Certificat Scolarité"',
        enrollment_app_step4: 'Choisir le semestre et cliquer "Télécharger PDF"',
        app_note: '💡 Le certificat via l\'APP a déjà le sceau électronique officiel !',
        enrollment_step1: 'Se connecter au portail d\'administration',
        enrollment_step2: 'Aller dans "Système d\'info académique" → "Statut Étudiant"',
        enrollment_step3: 'Choisir "Certificat semestre actuel" et télécharger',
        enrollment_step4: 'Confirmer le paiement des frais de scolarité',
        enrollment_step5: 'Apporter le reçu au Bureau (Frais : 10 NT$/copie)',
        enrollment_important_note: '⚠️ Important : Après paiement, le système peut prendre 2-3 jours ouvrables pour se mettre à jour.',
        go_to_portal: 'Aller au Portail →',
        residence_cert_title: '🏠 Comment obtenir la preuve de résidence',
        dorm_student: 'Étudiants en Dortoir :',
        residence_step1: 'Confirmer le paiement du dortoir',
        residence_step2: 'Se connecter au portail administratif',
        residence_step3: 'Télécharger l\'attestation depuis "Système Dortoir"',
        off_campus: 'Hors Campus :',
        rental_contract: 'Fournir le contrat de location signé avec le propriétaire',
        video_not_supported: 'Votre navigateur ne supporte pas la lecture vidéo',
        video1_caption: 'Voir comment créer un compte en ligne',
        video2_caption: 'Suivre la vidéo pour remplir le formulaire',
        video3_caption: 'Apprendre comment payer et retirer le titre',
        registration_steps: 'Étapes d\'inscription',
        reg_step1: 'Visiter le site de l\'Immigration : https://reurl.cc/GEbr2p',
        reg_step2: 'Cliquer sur "Enregistrer un nouveau compte"',
        reg_step3: 'Remplir les infos (passeport, contact, etc.)',
        reg_step4: 'Définir compte et mot de passe',
        reg_step5: 'Vérifier l\'email',
        reg_step6: 'Inscription terminée',
        application_steps: 'Étapes de demande',
        app_step1: 'Se connecter au système en ligne',
        app_step2: 'Choisir "Demande de Certificat de Résident Étranger"',
        app_step3: 'Remplir les informations personnelles',
        app_step4: 'Télécharger les documents :',
        upload_enrollment: 'Certificat de scolarité',
        upload_residence: 'Preuve de résidence',
        upload_photo: 'Fichier photo 2 pouces',
        app_step5: 'Confirmer les informations',
        app_step6: 'Soumettre la demande',
        permit_duration: '⏰ Durée du Titre',
        duration_note1: 'Première entrée sans inscription : 6 mois',
        duration_note2: 'Première entrée avec inscription : 1 an',
        duration_note3: 'Demander le renouvellement 3 mois avant expiration',
        payment_steps: 'Étapes de Paiement',
        pay_step1: 'Après la demande, un bordereau est généré',
        pay_step2: 'Imprimer le bordereau ou noter le code',
        pay_step3: 'Payer au dépanneur, poste ou banque (1 000 NT$)',
        pay_step4: 'Garder le reçu',
        pay_step5: 'Attendre l\'approbation (7-14 jours ouvrables)',
        pay_step6: 'Une fois notifié, aller à l\'Immigration avec passeport et reçu',
        congratulations: 'Félicitations !',
        completion_message: 'Vous avez réussi votre demande de titre de séjour !',
        important_reminders: '📌 Rappels Importants',
        reminder1: 'Renouveler 3 mois avant expiration',
        reminder2: 'Signaler changement d\'adresse sous 30 jours',
        reminder3: 'Amende 10k-50k NT$ si expiré',
        reminder4: 'Garder le titre en sécurité, signaler perte immédiatement',
        need_help: 'Besoin d\'aide ?',
        immigration_office: 'Bureau de l\'Immigration',
        immigration_website: 'Site Web : Système en ligne',
        school_office: 'NTNU Office of International Affairs',
        school_location: 'Lieu : Campus Heping, Bâtiment Général 1F',
        next_step: 'Suivant →',
        prev_step: '← Précédent',
        start_over: 'Recommencer',
        footer_text: '© 2026 NTNU - Guide de Titre de Séjour'
    },
    'de': {
        page_title: 'Leitfaden zur Beantragung einer Aufenthaltserlaubnis | Residence Permit Guide',
        main_title: 'Vollständiger Leitfaden für Aufenthaltserlaubnis',
        subtitle: 'Folgen Sie den Videos Schritt für Schritt',
        important_notice: 'Wichtiger Hinweis',
        notice_1: 'Online-Bewerbung',
        notice_2: 'Gesundheitsuntersuchung ist für den Erhalt erforderlich',
        notice_3: 'Abgelaufene Erlaubnis führt zu 10.000-50.000 NT$ Strafe',
        step1_title: 'Dokumente',
        step2_title: 'Konto',
        step3_title: 'Antrag',
        step4_title: 'Zahlung',
        step1_heading: 'Schritt 1: Notwendige Dokumente vorbereiten',
        step2_heading: 'Schritt 2: Einwanderungsbehörde-Konto registrieren',
        step3_heading: 'Schritt 3: Online-Formular ausfüllen',
        step4_heading: 'Schritt 4: Zahlung und Abholung',
        required_docs: 'Erforderliche Dokumente',
        doc_passport: 'Reisepass',
        doc_passport_desc: 'Original und Kopie',
        doc_visa: 'Aufenthaltsvisum',
        doc_visa_desc: 'Visum mit Vermerk "Foreign Student"',
        doc_enrollment: 'Immatrikulationsbescheinigung',
        doc_enrollment_desc: 'Nach Registrierung herunterladen oder im Büro beantragen',
        doc_residence: 'Wohnsitznachweis',
        doc_residence_desc: 'Wohnheimbescheinigung oder Mietvertrag',
        doc_photo: 'Foto',
        doc_photo_desc: '2-Zoll-Foto, weißer Hintergrund, ohne Kopfbedeckung',
        doc_fee: 'Gebühr',
        doc_fee_desc: '1.000 NT$ (1 Jahr gültig)',
        enrollment_cert_title: '📄 Wie man die Immatrikulationsbescheinigung erhält',
        method1: 'Methode 1: Über NTNU & App (Empfohlen)',
        method2: 'Methode 2: i-Portal Web-Download',
        method3: 'Methode 3: Im Registrierungsbüro',
        enrollment_app_step1: '"NTNU APP" herunterladen und einloggen',
        enrollment_app_step2: 'Gehe zu "Mein Campus" → "Studentenzone"',
        enrollment_app_step3: 'Wähle "Akademische Infos" → "Bescheinigung"',
        enrollment_app_step4: 'Semester wählen und "PDF herunterladen" klicken',
        app_note: '💡 App-Zertifikate haben bereits einen digitalen Stempel!',
        enrollment_step1: 'Im Schulverwaltungsportal einloggen',
        enrollment_step2: 'Zu "Akademisches Infosystem" → "Studentenstatus"',
        enrollment_step3: '"Bescheinigung aktuelles Semester" wählen und laden',
        enrollment_step4: 'Bestätigen, dass Studiengebühren bezahlt sind',
        enrollment_step5: 'Quittung zum Büro bringen (Gebühr: 10 NT$/Kopie)',
        enrollment_important_note: '⚠️ Wichtig: Nach Zahlung kann das System 2-3 Werktage zur Aktualisierung benötigen.',
        go_to_portal: 'Zum Portal →',
        residence_cert_title: '🏠 Wie man den Wohnsitznachweis erhält',
        dorm_student: 'Wohnheimstudenten:',
        residence_step1: 'Zahlung der Wohnheimgebühren bestätigen',
        residence_step2: 'Im Verwaltungsportal einloggen',
        residence_step3: 'Bescheinigung vom "Wohnheimsystem" laden',
        off_campus: 'Außerhalb des Campus:',
        rental_contract: 'Mietvertrag mit Vermieterunterschrift vorlegen',
        video_not_supported: 'Ihr Browser unterstützt keine Videowiedergabe',
        video1_caption: 'Video zur Kontoregistrierung ansehen',
        video2_caption: 'Video zum Ausfüllen des Antrags folgen',
        video3_caption: 'Zahlung und Abholung lernen',
        registration_steps: 'Registrierungsschritte',
        reg_step1: 'Website der Einwanderungsbehörde: https://reurl.cc/GEbr2p',
        reg_step2: 'Klicken Sie auf "Neues Konto registrieren"',
        reg_step3: 'Persönliche Daten ausfüllen',
        reg_step4: 'Benutzerkonto und Passwort festlegen',
        reg_step5: 'E-Mail verifizieren',
        reg_step6: 'Registrierung abschließen',
        application_steps: 'Antragsschritte',
        app_step1: 'Im Online-System einloggen',
        app_step2: '選擇「外僑居留證申請」',
        app_step3: 'Persönliche Daten ausfüllen',
        app_step4: 'Dokumente hochladen:',
        upload_enrollment: 'Immatrikulationsbescheinigung',
        upload_residence: 'Wohnsitznachweis',
        upload_photo: '2-Zoll-Fotodatei',
        app_step5: 'Informationen bestätigen',
        app_step6: 'Antrag absenden',
        permit_duration: '⏰ Gültigkeitsdauer',
        duration_note1: 'Erste Einreise ohne Registrierung: 6 Monate',
        duration_note2: 'Erste Einreise mit Registrierung: 1 Jahr',
        duration_note3: 'Verlängerung 3 Monate vor Ablauf beantragen',
        payment_steps: 'Zahlungsschritte',
        pay_step1: 'Nach Antragstellung wird ein Zahlschein erstellt',
        pay_step2: 'Schein drucken oder Code notieren',
        pay_step3: 'Im Konbini, Post oder Bank zahlen (1.000 NT$)',
        pay_step4: 'Zahlungsbeleg aufbewahren',
        pay_step5: 'Genehmigung abwarten (ca. 7-14 Werktage)',
        pay_step6: 'Mit Pass und Beleg zur Behörde gehen',
        congratulations: 'Glückwunsch!',
        completion_message: 'Sie haben die Aufenthaltserlaubnis erfolgreich beantragt!',
        important_reminders: '📌 Wichtige Erinnerungen',
        reminder1: 'Verlängerung 3 Monate vor Ablauf',
        reminder2: 'Adressänderung innerhalb 30 Tagen melden',
        reminder3: 'Strafe bei Ablauf 10k-50k NT$',
        reminder4: 'Karte sicher aufbewahren, Verlust sofort melden',
        need_help: 'Hilfe benötigt?',
        immigration_office: 'Einwanderungsbehörde',
        immigration_website: 'Website: Online-System',
        school_office: 'NTNU Office of International Affairs',
        school_location: 'Ort: Heping Campus, Allgemeines Gebäude 1. Stock',
        next_step: 'Nächster Schritt →',
        prev_step: '← Zurück',
        start_over: 'Neu starten',
        footer_text: '© 2026 NTNU - Leitfaden für ausländische Studenten'
    },
    'ru': {
        page_title: 'Руководство по получению ВНЖ для студентов | Residence Permit Guide',
        main_title: 'Полное руководство по получению ВНЖ',
        subtitle: 'Следуйте видео шаг за шагом',
        important_notice: 'Важное уведомление',
        notice_1: 'Онлайн-заявка',
        notice_2: 'Для получения ВНЖ необходимо пройти медосмотр',
        notice_3: 'Штраф за просрочку ВНЖ: 10 000-50 000 NT$',
        step1_title: 'Документы',
        step2_title: 'Регистрация',
        step3_title: 'Заявка',
        step4_title: 'Оплата',
        step1_heading: 'Шаг 1: Подготовка документов',
        step2_heading: 'Шаг 2: Регистрация аккаунта',
        step3_heading: 'Шаг 3: Заполнение онлайн-формы',
        step4_heading: 'Шаг 4: Оплата и получение',
        required_docs: 'Список документов',
        doc_passport: 'Паспорт',
        doc_passport_desc: 'Оригинал и копия',
        doc_visa: 'Резидентская виза',
        doc_visa_desc: 'Виза с пометкой "Foreign Student"',
        doc_enrollment: 'Справка об обучении',
        doc_enrollment_desc: 'Скачать после регистрации или получить в офисе',
        doc_residence: 'Подтверждение проживания',
        doc_residence_desc: 'Справка из общежития или договор аренды',
        doc_photo: 'Фото',
        doc_photo_desc: '2-дюймовое фото на белом фоне',
        doc_fee: 'Сбор',
        doc_fee_desc: '1 000 NT$ (на 1 год)',
        enrollment_cert_title: '📄 Как получить справку об обучении',
        method1: 'Способ 1: Через приложение NTNU (Рекомендуется)',
        method2: 'Способ 2: Через сайт i-Portal',
        method3: 'Способ 3: В учебном офисе',
        enrollment_app_step1: 'Скачайте и войдите в "NTNU APP"',
        enrollment_app_step2: 'Зайдите в "My Campus" → "Student Zone"',
        enrollment_app_step3: 'Выберите "Academic Info" → "Enrollment Certificate"',
        enrollment_app_step4: 'Выберите семестр и нажмите "Download PDF"',
        app_note: '💡 Справка из приложения уже имеет электронную печать!',
        enrollment_step1: 'Войдите в школьный портал',
        enrollment_step2: 'Перейдите в "Academic Information System"',
        enrollment_step3: 'Скачайте справку за текущий семестр',
        enrollment_step4: 'Убедитесь, что обучение оплачено',
        enrollment_step5: 'Принесите квитанцию в офис (Цена: 10 NT$/копия)',
        enrollment_important_note: '⚠️ Важно: После оплаты системе может потребоваться 2-3 дня для обновления.',
        go_to_portal: 'Перейти на портал →',
        residence_cert_title: '🏠 Как получить подтверждение проживания',
        dorm_student: 'Студенты в общежитии:',
        residence_step1: 'Подтвердите оплату общежития',
        residence_step2: 'Войдите в административный портал',
        residence_step3: 'Скачайте справку из "Dormitory System"',
        off_campus: 'Вне кампуса:',
        rental_contract: 'Предоставьте договор аренды с подписью владельца',
        video_not_supported: 'Ваш браузер не поддерживает видео',
        video1_caption: 'Посмотрите видео о регистрации аккаунта',
        video2_caption: 'Следуйте видео для заполнения формы',
        video3_caption: 'Узнайте об оплате и получении карты',
        registration_steps: 'Шаги регистрации',
        reg_step1: 'Сайт Иммиграционной службы: https://reurl.cc/GEbr2p',
        reg_step2: 'Нажмите "Register New Account"',
        reg_step3: 'Заполните личные данные',
        reg_step4: 'Установите логин и пароль',
        reg_step5: 'Подтвердите email',
        reg_step6: 'Регистрация завершена',
        application_steps: 'Шаги подачи заявки',
        app_step1: 'Войдите в онлайн-систему',
        app_step2: 'Выберите "Alien Residence Certificate Application"',
        app_step3: 'Заполните личные данные',
        app_step4: 'Загрузите документы:',
        upload_enrollment: 'Справка об обучении',
        upload_residence: 'Подтверждение проживания',
        upload_photo: '2-дюймовое фото',
        app_step5: 'Подтвердите информацию',
        app_step6: 'Отправьте заявку',
        permit_duration: '⏰ Срок действия',
        duration_note1: 'Первый въезд без регистрации: 6 месяцев',
        duration_note2: 'Первый въезд с регистрацией: 1 год',
        duration_note3: 'Продление за 3 месяца до истечения',
        payment_steps: 'Шаги оплаты',
        pay_step1: 'После заявки будет создан квитанция',
        pay_step2: 'Распечатайте или запишите код',
        pay_step3: 'Оплатите в магазине, на почте или в банке (1 000 NT$)',
        pay_step4: 'Сохраните чек',
        pay_step5: 'Ждите одобрения (7-14 рабочих дней)',
        pay_step6: 'Получите карту в офисе с паспортом и чеком',
        congratulations: 'Поздравляем!',
        completion_message: 'Вы успешно подали заявку на ВНЖ Тайваня!',
        important_reminders: '📌 Важные напоминания',
        reminder1: 'Продлевайте за 3 месяца до конца',
        reminder2: 'Сообщайте о смене адреса за 30 дней',
        reminder3: 'Штраф за просрочку 10k-50k NT$',
        reminder4: 'Берегите карту, при утере сообщите немедленно',
        need_help: 'Нужна помощь?',
        immigration_office: 'Иммиграционная служба',
        immigration_website: 'Сайт: Онлайн-система',
        school_office: 'NTNU Office of International Affairs',
        school_location: 'Место: Кампус Heping, Общее здание 1 эт.',
        next_step: 'Далее →',
        prev_step: '← Назад',
        start_over: 'Начать заново',
        footer_text: '© 2026 NTNU - Руководство для иностранных студентов'
    }
};

let currentLang = 'zh-TW';
let currentStep = 1;

// =====================================
// Initialize
// =====================================
document.addEventListener('DOMContentLoaded', () => {
    initLanguage();
    initNav();
    updateProgress();
});

// =====================================
// Language Functions
// =====================================
function initLanguage() {
    const savedLang = localStorage.getItem('selectedLanguage') || 'zh-TW';
    // Ensure translations exist before switching
    if (typeof translations !== 'undefined' && translations[savedLang]) {
        switchLanguage(savedLang);
    } else {
        switchLanguage('zh-TW');
    }

    const btns = document.querySelectorAll('.lang-btn');
    if (btns.length === 0) {
        console.warn('No language buttons found');
        return;
    }

    btns.forEach(btn => {
        // Remove old listeners (if any mechanism existed to do so, strictly speaking we can't easily, 
        // but adding new ones is fine as this runs once on DOMContentLoaded)
        btn.onclick = function() { // Use onclick property to avoid duplicate listeners if run multiple times
            const lang = this.getAttribute('data-lang');
            if (lang) {
                switchLanguage(lang);
            }
        };
    });
}

function switchLanguage(lang) {
    if (!translations[lang]) {
        lang = 'zh-TW';
    }

    currentLang = lang;
    localStorage.setItem('selectedLanguage', lang);

    // Update active button
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.toggle('active', btn.dataset.lang === lang);
    });

    // Update all translatable elements
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.dataset.i18n;
        if (translations[lang][key]) {
            if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
                el.placeholder = translations[lang][key];
            } else {
                el.textContent = translations[lang][key];
            }
        }
    });

    // Update page title
    document.title = translations[lang].page_title;
}

// =====================================
// Navigation Functions
// =====================================
function initNav() {
    // Mark completed steps
    updateStepStatus();
}

function nextStep() {
    if (currentStep < 4) {
        currentStep++;
        showStep(currentStep);
        updateProgress();
        updateStepStatus();
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }
}

function prevStep() {
    if (currentStep > 1) {
        currentStep--;
        showStep(currentStep);
        updateProgress();
        updateStepStatus();
        window.scrollTo({ top: 0, behavior: 'smooth' });
    }
}

function showStep(step) {
    // Hide all step contents
    document.querySelectorAll('.step-content').forEach(content => {
        content.classList.remove('active');
    });

    // Show current step content
    const stepContent = document.querySelector(`.step-content[data-content="${step}"]`);
    if (stepContent) {
        stepContent.classList.add('active');
    }

    // Update step indicators
    document.querySelectorAll('.step').forEach((el, index) => {
        el.classList.toggle('active', index + 1 === step);
    });
}

function updateProgress() {
    const progressFill = document.getElementById('progressFill');
    const percentage = (currentStep / 4) * 100;
    progressFill.style.width = `${percentage}%`;
}

function updateStepStatus() {
    document.querySelectorAll('.step').forEach((el, index) => {
        const stepNum = index + 1;
        if (stepNum < currentStep) {
            el.classList.add('completed');
        } else {
            el.classList.remove('completed');
        }
    });
}

function resetGuide() {
    currentStep = 1;
    showStep(1);
    updateProgress();
    updateStepStatus();
    window.scrollTo({ top: 0, behavior: 'smooth' });
}
